apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access via the Docker container name
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
